services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookvault
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dockerInitTestDb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db        
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: